


CREATE TABLE PERSONAS (
  cod INT NOT NULL, 
  dsc NVARCHAR(100) NOT NULL, 
  codpersrel INT NOT NULL, 
  tipopers SMALLINT NOT NULL, 
  codorigen INT NOT NULL, 
  fila INT NOT NULL, 
  PRIMARY KEY (cod)
);






INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30727, N'Jarmatz Hnos', 0, 1, 1, 20);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30728, N'Marta Rosa y Natalio Hector (Eco) Kanzepolsky', 0, 1, 1, 21);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30729, N'Benjamin Wapñarsky', 0, 1, 1, 22);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30731, N'Faustino Scarafía', 0, 1, 1, 23);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30732, N'José Daitch', 0, 1, 1, 24);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30733, N'Bernardo Jesiot', 0, 1, 1, 25);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30735, N'Javier Becker', 0, 1, 0, 6327);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30736, N'Héctor Mondrik', 0, 1, 0, 6328);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30737, N'Catalina Jarmatz', 0, 1, 1, 26);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30738, N'Museo histórico Comunal', 0, 1, 1, 27);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30739, N'Isaac Kaplan', 0, 1, 1, 28);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30740, N'Orlando Coniglio', 0, 1, 1, 29);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30741, N'Sacarias Rabinsky', 0, 1, 1, 30);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30742, N'Fridman Marcos', 0, 1, 1, 31);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30743, N'Adolfo Blumental', 0, 1, 1, 32);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30744, N'Lipe Notkovich', 0, 1, 1, 33);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30745, N'Familia Cohn', 0, 1, 1, 34);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30746, N'Familia Elkan', 0, 1, 1, 35);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30748, N'Bernardo Kaplan', 0, 0, 0, 0);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30749, N'Sofía de Matzkin', 0, 1, 1, 38);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30750, N'Marta Katz', 0, 1, 1, 39);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30751, N'Sara Jeifetz de Rosado', 0, 1, 1, 40);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30752, N'Esteban Fritzler', 0, 1, 1, 41);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30753, N'Tili de Gun', 0, 1, 1, 42);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30754, N'Ruth de Nusbaum', 0, 1, 1, 43);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30755, N'Clara Gontmaher de Eidelman', 0, 1, 1, 44);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30759, N'Jacobo Werbin', 0, 1, 1, 48);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30760, N'Mario Malajovich', 0, 1, 1, 49);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30761, N'Colegio Nacional', 0, 1, 1, 50);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30762, N'Gunter Fritzler', 0, 1, 1, 51);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30763, N'Esteher de Jarovsky', 0, 1, 1, 52);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30764, N'Sociedad Kadima', 0, 1, 1, 53);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30766, N'Moisés Joskovich', 0, 1, 1, 55);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30767, N'Teitelbaum Jaime', 0, 1, 1, 56);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30768, N'Ernesto Jeifetz', 0, 1, 1, 57);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30769, N'Tissembaum Marcelo', 0, 1, 1, 58);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30771, N'Fanny de Kanzepolsky', 0, 1, 1, 60);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30772, N'Naum Guelbert', 0, 1, 1, 61);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30773, N'Noe Kurdobrin', 0, 1, 1, 62);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30774, N'Oreste Panigutti', 0, 1, 1, 63);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30775, N'Liliana de Schlaien', 0, 1, 1, 64);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30776, N'Familia Khol', 0, 1, 1, 65);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30777, N'Freume Mitnik', 0, 1, 1, 66);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30778, N'Doris Kovalsky', 0, 1, 1, 67);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30779, N'Ester Tissembaum', 0, 1, 1, 68);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30780, N'Eva de Rosenthal', 0, 1, 1, 69);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30781, N'Pedro Smulovich', 0, 1, 1, 70);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30782, N'Nosem Trumper', 0, 1, 1, 71);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30783, N'Enrique Kulemeyer', 0, 1, 1, 72);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30784, N'Matilde Silberman', 0, 1, 1, 73);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30785, N'Elena de Cosentino', 0, 1, 0, 6333);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30786, N'Inés Faín', 0, 1, 0, 6334);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30787, N'Familia  Weisburd', 0, 1, 0, 6335);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30788, N'Kovalsky Mauricio', 0, 1, 0, 6336);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30789, N'Isaac Salimson', 0, 1, 0, 6337);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30790, N'Aaron Stifelman', 0, 1, 0, 6338);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30791, N'Mario Schapchuk', 0, 1, 0, 6339);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30792, N'Ministerio de Instrucción Pública y fomento', 0, 1, 0, 6340);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30793, N'José Bernardo Arcavi', 0, 1, 0, 6341);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30794, N'bertoldo Baer', 0, 1, 0, 6342);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30795, N'Felipe Schilman', 0, 1, 0, 6343);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30796, N'José y Rasche Schapira', 0, 1, 0, 6343);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30798, N'Horacio Monutti', 0, 1, 0, 6345);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30799, N'Leiser Levisman de Fischer', 0, 1, 0, 6346);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30800, N'Aaron Jeifetz', 0, 1, 0, 6347);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30801, N'Adolfo Levisman', 0, 1, 0, 6348);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30803, N'Familiares de Abraham Leibovich', 0, 1, 0, 6349);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30804, N'Pablo Trumper', 0, 1, 0, 6349);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30805, N'José e Isidoro (Suger) Gun', 0, 1, 0, 6350);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30806, N'Ines Lowenstein', 0, 1, 0, 6351);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30807, N'Marta Berghausen de Rosenthal', 0, 1, 0, 6352);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30809, N'Jorge Mehring', 0, 1, 0, 6354);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30810, N'Frida Trumper de Gelburt', 0, 1, 0, 6355);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30811, N'Margarita Aranda.', 0, 1, 0, 6356);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30812, N'Familia  Salzman Dehovna', 0, 1, 0, 6356);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30813, N'Raquel y Miguel Morkovsky', 0, 1, 0, 6357);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30814, N'Juanita Aronovich de Guelbert', 0, 1, 0, 6358);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30815, N'Familia  Seiferheld', 0, 1, 0, 6359);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30816, N'Beatriz  Levisman de Kaplan', 0, 1, 0, 6360);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30817, N'Adela Ulis de Sexer', 0, 1, 0, 6361);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30819, N'Teresita Gelburt', 0, 1, 0, 6363);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30820, N'Mario y Porota Ambasch', 0, 1, 0, 6364);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30821, N'Aizik Blumenfeld', 0, 1, 0, 6365);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30822, N'Ferretería Kurman', 0, 1, 0, 6366);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30824, N'Manfredo Wolf', 0, 1, 0, 6367);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30825, N'Escuela Nacional N° 6054', 0, 1, 0, 6368);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30826, N'Ariel Nisnevich', 0, 1, 0, 6369);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30829, N'Isaac Mijamkin', 0, 1, 0, 6370);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30832, N'Clara Sandler de Ambasch', 0, 1, 0, 6371);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30833, N'Familia Frank - Lowenstein', 0, 1, 0, 6372);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30836, N'Berta y Sally  Lowenstein', 0, 1, 0, 6373);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30837, N'Guillermo Servini', 0, 1, 0, 6374);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30838, N'Galagosvsky Moishe', 0, 1, 0, 6374);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30839, N'Matrimonio Frank', 0, 1, 0, 6374);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30840, N'Leonardo Lowenstein', 0, 1, 0, 6376);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30841, N'Familia Jarmatz', 0, 1, 0, 6378);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30842, N'Lía Susana Marmai', 0, 1, 0, 6379);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30844, N'Helga Fritzler de Cohon', 0, 1, 0, 6380);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30845, N'León Silberman', 0, 1, 0, 6381);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30846, N'Jose Ben Raken', 0, 1, 0, 6382);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30847, N'Irico Boeris', 0, 1, 0, 6382);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30850, N'Mario Enrique Ibañez', 0, 1, 0, 6383);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30851, N'Familia Werbin', 0, 1, 0, 6384);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30852, N'Dibujante Plano', 0, 1, 0, 6385);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30853, N'Mirski', 0, 1, 0, 6386);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30854, N'La Mutua Agrícola', 0, 1, 0, 6387);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30856, N'Mario Eidelman', 0, 1, 0, 6388);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30858, N'Flia Kulemeyer', 0, 1, 0, 6389);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30859, N'Raquel Brestovitzky de Galagovsky', 0, 1, 0, 6390);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30860, N'Museo Judío Salvador Kibrik Bs.As.', 0, 1, 0, 6391);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30861, N'Jacobo Blumenfeld', 0, 1, 0, 6392);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30862, N'León Blumenfeld', 0, 1, 0, 6393);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30863, N'JCA', 0, 1, 0, 6394);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30864, N'Comuna de Moises Ville', 0, 1, 0, 6394);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30867, N'Kaplan Pablo y Mery Blumenfeld', 0, 1, 0, 6394);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30868, N'Ganaderos Unidos S.A.', 0, 1, 0, 6394);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30869, N'Ana Gerson', 0, 1, 0, 6395);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30870, N'Norma (Chuchi) Novik de Joison', 0, 1, 0, 6396);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30872, N'Flia de Jorge Gauna', 0, 1, 0, 6397);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30873, N'Mikel Asensio', 0, 1, 0, 6397);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30874, N'Elena Pol', 0, 1, 0, 6398);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30875, N'Naún', 0, 1, 0, 6399);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30876, N'Naún Saks y Sra.', 0, 1, 0, 6399);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30877, N'Blume Dujovne de Werbin', 0, 1, 0, 6401);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30878, N'Helga de Cohn', 0, 1, 0, 6402);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30879, N'Lote de Wildan.', 0, 1, 0, 6403);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30880, N'Hector Sandler', 0, 1, 0, 6404);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30881, N'Carlota Grosvald de Singer', 0, 1, 0, 6405);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30882, N'Jae Fridman', 0, 1, 0, 6406);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30883, N'Miguel Floreal Periales', 0, 1, 0, 6407);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30884, N'Sofía Blumenfeld de Gun', 0, 1, 0, 6408);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30885, N'Comunidad Mutual Israelita', 0, 1, 0, 6409);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30887, N'Berta de Tilinger.', 0, 1, 0, 6411);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30888, N'Clara Gentoff de Kleiman.', 0, 1, 0, 6412);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30889, N'Golde de Burijovich', 0, 1, 0, 6413);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30890, N'Juan Carlos Espindola (Pachi)', 0, 1, 0, 6414);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30891, N'depositante', 0, 1, 0, 6415);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30892, N'Herman Gerson', 0, 1, 0, 6415);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30893, N'Nora Kaplan de Gaisiner', 0, 1, 0, 6416);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30894, N'Isaac Trumper', 0, 1, 0, 6417);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30895, N'Jacobo Galagovsky', 0, 1, 0, 6417);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30896, N'Isidro Guelbert', 0, 1, 0, 6418);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30897, N'Angel Beltramo', 0, 1, 0, 6419);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30899, N'Julio Hamershlag.', 0, 1, 0, 6420);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30901, N'Abraham Kanzepolsky', 0, 1, 0, 6420);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30902, N'Taibe Trumper.', 0, 1, 0, 6421);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30903, N's8', 0, 1, 0, 6422);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30904, N's8i', 0, 1, 0, 6422);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30905, N'Flia. Glasberg.', 0, 1, 0, 6422);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30906, N'Solita  Felpin de Glukman.', 0, 1, 0, 6422);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30907, N'Sholem Tissembaum.', 0, 1, 0, 6423);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30908, N'Norma Caseres de Poggio', 0, 1, 0, 6424);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30909, N'Golde Gerson', 0, 1, 0, 6424);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30910, N'Miguel Grines', 0, 1, 0, 6425);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30912, N'David Jarovsky', 0, 1, 0, 6426);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30913, N'Flia Jeifetz', 0, 1, 0, 6427);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30914, N'Fritz Laster.', 0, 1, 0, 6428);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30915, N'NIsel Eidelman', 0, 1, 0, 6429);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30916, N'Sofia Veigman', 0, 1, 0, 6429);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30917, N'Lea Rais', 0, 1, 0, 6430);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30918, N'Juana Werbin de Ambasch', 0, 1, 0, 6431);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30919, N'Scarafía Celina', 0, 1, 0, 6432);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30920, N'Familiares de Isaac Arcavi', 0, 1, 0, 6433);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30921, N'Dora de Ambasch', 0, 1, 0, 6433);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30922, N'Alter AMBASCH', 0, 1, 0, 6434);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30923, N'Samuel Kanzepolsky', 0, 1, 0, 6435);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30924, N'Tzive Kurman de Krupic', 0, 1, 0, 6437);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30925, N'Ana Kurman', 0, 1, 0, 6437);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30926, N'Gabriela Merli', 0, 1, 0, 6439);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30930, N'Benzion Wald', 0, 1, 0, 6440);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30931, N'Leizer Elman', 0, 1, 0, 6441);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30932, N'Orfelina Periale', 0, 1, 0, 6441);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30934, N'Sinagoga Israelita Azquenazi', 0, 1, 0, 6442);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30935, N'Max Fritzler', 0, 1, 0, 6442);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30936, N'Jacinta Kanzepolsky.', 0, 1, 0, 6443);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30937, N'Alberto Lowenstein', 0, 1, 0, 6444);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30938, N'Mario José Sanchez', 0, 1, 0, 6445);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30939, N'Jaime  Staravolsky', 0, 1, 0, 6446);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30940, N'Malke Bloj', 0, 1, 0, 6447);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30941, N'León Silberman', 0, 1, 0, 6448);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30942, N'Strass Luis', 0, 1, 0, 6449);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30943, N'Miguel Trumper.', 0, 1, 0, 6450);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30944, N'Aida de Gentoff', 0, 1, 0, 6451);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30945, N'Kata Sterman', 0, 1, 0, 6452);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30946, N'Abraham Reisin', 0, 1, 0, 6452);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30947, N'Abraham y Berta Arcavi', 0, 1, 0, 6452);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30948, N'Faustino Quiroga', 0, 1, 0, 6453);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30949, N'Sara Etel Pletnitzky', 0, 1, 0, 6454);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30950, N'Leonor Kulemeyer', 0, 1, 0, 6455);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30951, N'Kety Blum', 0, 1, 0, 6456);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30952, N'Ana  Azaretzky de Ribak', 0, 1, 0, 6457);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30953, N'Issac Salimsom', 0, 1, 0, 6458);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30954, N'Norberto Morlachi', 0, 1, 0, 6459);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30955, N'Sujer Gun', 0, 1, 0, 6460);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30956, N'Pablo Novick', 0, 1, 0, 6461);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30957, N'Sofía Bloj', 0, 1, 0, 6461);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30958, N'Catalina D. de Leibovich', 0, 1, 0, 6462);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30959, N'Nilda Baretta de Cecotti y Adela Baretta de Coniglio', 0, 1, 0, 6463);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30961, N'Elsa Golber de Goldstein', 0, 1, 0, 6465);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30962, N'Fanny Temkin', 0, 1, 0, 6466);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30963, N'Martha Rosenthal', 0, 1, 0, 6467);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30964, N'Guillermo Katz', 0, 1, 0, 6468);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30965, N'Moisés Glombosky.', 0, 1, 0, 6469);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30966, N'Moisés Singer', 0, 1, 0, 6470);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30967, N'Ernesto Leivobich', 0, 1, 0, 6470);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30968, N'Sara Binder', 0, 1, 0, 6471);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30969, N'José Galagovsky', 0, 1, 0, 6472);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30970, N'Helga Kohn', 0, 1, 0, 6473);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30971, N'Belkis de Hamerschlag', 0, 1, 0, 6474);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30972, N'Kurt Rosenthal y Eva Guelbert de', 0, 1, 0, 6475);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30973, N'Betti Zocol de Woloschin', 0, 1, 0, 6476);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30974, N'Thi', 0, 1, 0, 6477);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30975, N'Rebeca Berestein', 0, 1, 0, 6477);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30976, N'Seminario de Maestros Hebreos de la Amia', 0, 1, 0, 6478);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30977, N'Rebeca de Zadunaisky', 0, 1, 0, 6479);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30978, N'Heiman Grumwald', 0, 1, 0, 6480);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30979, N'Soc. Coop. Socorro Fraternal', 0, 1, 0, 6481);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30980, N'Belkys Kleiman', 0, 1, 0, 6481);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30981, N'Dorita Trumper', 0, 1, 0, 6482);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30982, N'Nylda gonzales de Trumper', 0, 1, 0, 6483);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30984, N'Rosa Barck de Narovsky', 0, 1, 0, 6484);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30985, N'Soc. A.Ganaderos Unidos de Moisés Ville', 0, 1, 0, 6484);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30986, N'Raquel Morcovsky', 0, 1, 0, 6484);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30987, N'Azucena de Bechio', 0, 1, 0, 6485);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30988, N'Chianone Guillermo', 0, 1, 0, 6486);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30989, N'Moisés Notkovich', 0, 1, 0, 6487);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30990, N'SanCor Moisés Ville', 0, 1, 0, 6488);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30991, N'Granjeros Unidos', 0, 1, 0, 6488);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30992, N'Fraternidad Agraria', 0, 1, 0, 6488);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30993, N'Mario Teitelbaum', 0, 1, 0, 6488);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30994, N'Coop. Agrícola de consumo Santa Rosa', 0, 1, 0, 6489);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30995, N'Casa Coop. de previsión Sunchales Ltda.', 0, 1, 0, 6489);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30996, N'Banco Litoral Coop. Ltdo.', 0, 1, 0, 6489);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30997, N'Sancor  Coop. de seguros Ltda.', 0, 1, 0, 6489);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30998, N'Joyería Ric-Ser-Dan', 0, 1, 0, 6489);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (30999, N'Coop. Ganadera Ltda. de Capivara', 0, 1, 0, 6489);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31000, N'Coop. Agríc. Gan. y de consumo Bernasconi', 0, 1, 0, 6489);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31001, N'José Bechio', 0, 1, 0, 6489);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31002, N'Colombo y Magliano S.A.', 0, 1, 0, 6490);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31003, N'Teresa Runstein de  Brufman', 0, 1, 0, 6490);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31004, N'Beatriz de Woloschin', 0, 1, 0, 6490);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31006, N'Goldina de Gerson', 0, 1, 0, 6491);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31007, N'Ingue Kanzepolsky', 0, 1, 0, 6492);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31010, N'Juan Domingo Grande', 0, 1, 0, 6492);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31011, N'María Teresa  Minetti', 0, 1, 0, 6493);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31012, N'Romina Vanesa Liebembuk', 0, 1, 0, 6494);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31013, N'José Arcavi', 0, 1, 0, 6495);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31014, N'Sara Aranovich', 0, 1, 0, 6496);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31015, N'Salman y Jarmatz', 0, 1, 0, 6496);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31016, N'Margarita de Rabinovich', 0, 1, 0, 6497);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31019, N'José Pedroni', 0, 1, 0, 6500);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31021, N'Velmiro Ayala Gauna', 0, 1, 0, 6501);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31022, N'EVE CURIE', 0, 1, 0, 6502);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31023, N'Federación Argentina de Coop. de consumo', 0, 1, 0, 6503);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31024, N'Autores Argentino', 0, 1, 0, 6503);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31025, N'juventud Israelita', 0, 1, 0, 6503);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31026, N'Howard Fast', 0, 1, 0, 6504);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31027, N'Daniel Rops', 0, 1, 0, 6505);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31028, N'Domingo Faustino Sarmiento', 0, 1, 0, 6506);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31029, N'Arturo Capdevila', 0, 1, 0, 6507);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31030, N'Gustavo A. Bérquer', 0, 1, 0, 6508);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31031, N'Enrique Larreta', 0, 1, 0, 6509);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31032, N'Francois Mauriac', 0, 1, 0, 6510);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31034, N'Ricardo Rojas', 0, 1, 0, 6512);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31035, N'Bernardo Delón', 0, 1, 0, 6513);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31036, N'Ricardo Setaro', 0, 1, 0, 6514);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31037, N'George Orwell', 0, 1, 0, 6515);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31038, N'Lin Yutang', 0, 1, 0, 6516);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31039, N'John Steinbech', 0, 1, 0, 6517);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31040, N'Julio Minio', 0, 1, 0, 6518);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31041, N'León Uris', 0, 1, 0, 6519);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31042, N'Erna C. Schlesinger', 0, 1, 0, 6520);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31044, N'Mario Rotemberg', 0, 1, 0, 6522);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31045, N'Carlos Bogovich', 0, 1, 0, 6523);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31046, N'Catalina  de Cociovich', 0, 1, 0, 6524);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31047, N'Boris Rejovisky', 0, 1, 0, 6525);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31048, N'Sholem Asch', 0, 1, 0, 6526);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31049, N'Jorge Amado', 0, 1, 0, 6527);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31050, N'M. Delly', 0, 1, 0, 6528);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31052, N'Isaias Leo Kremer', 0, 1, 0, 6529);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31053, N'Jorge A. Propato', 0, 1, 0, 6530);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31054, N'B. Drimer', 0, 1, 0, 6531);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31055, N'Editorial La Frontera', 0, 1, 0, 6532);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31056, N'Jorge Campana', 0, 1, 0, 6532);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31057, N'Boris Zinger', 0, 1, 0, 6533);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31058, N'Escuela Fiscal 462', 0, 1, 0, 6533);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31059, N'Teresa R. de Brufman', 0, 1, 0, 6533);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31061, N'Lilian Cataneo', 0, 1, 0, 6535);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31062, N'Ida V de Waisman', 0, 1, 0, 6535);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31063, N'Mauricio Brufman', 0, 1, 0, 6536);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31064, N'A. Ilantiel', 0, 1, 0, 6537);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31065, N'Julia Gorbatin de Wieder', 0, 1, 0, 6537);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31066, N'Berta de Epstein', 0, 1, 0, 6538);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31067, N'Biblioteca Barón Hirsch', 0, 1, 0, 6538);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31069, N'Nestor  Kansepolsky', 0, 1, 0, 6539);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31070, N'Jacobo Rejontzky', 0, 1, 0, 6540);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31071, N'jacobo Resnik', 0, 1, 0, 6541);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31072, N'Guillermo Luis Fradegrade', 0, 1, 0, 6542);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31073, N'Damas Israelita', 0, 1, 0, 6543);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31074, N'Harry Pluda', 0, 1, 0, 6543);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31075, N'Sociedad Lejem Evioinim', 0, 1, 0, 6544);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31076, N'Moisés Gutman', 0, 1, 0, 6544);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31077, N'Beatriz de Villarruel', 0, 1, 0, 6545);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31078, N'Maximiliano Villarruel', 0, 1, 0, 6546);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31079, N'Seminario "Iosef Draznin"', 0, 1, 0, 6547);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31080, N'Jorge y Lucy Galagovsky', 0, 1, 0, 6547);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31081, N'Banco Comercial Israelita', 0, 1, 0, 6548);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31082, N'Froimovich Nora', 0, 1, 0, 6548);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31084, N'Miguel  Kaplansky', 0, 1, 0, 6551);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31086, N'Nieves de Glasberg', 0, 1, 0, 6553);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31087, N'Pinjus Mendelew', 0, 1, 0, 6554);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31088, N'Grande Celestino', 0, 1, 0, 6555);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31089, N'Fernando Hector Goldman', 0, 1, 0, 6556);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31090, N'Juana Gun', 0, 1, 0, 6557);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31091, N'Flia Silberman', 0, 1, 0, 6558);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31092, N'Temkin Salomón', 0, 1, 0, 6559);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31093, N'Nahama  Goldman', 0, 1, 0, 6560);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31094, N'Dorita y Marcos Trumper', 0, 1, 0, 6561);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31095, N'Judit Kindel de Capellano', 0, 1, 0, 6562);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31096, N'Flia de José Scarafía', 0, 1, 0, 6563);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31097, N'Glembotsky  Tania', 0, 1, 0, 6564);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31098, N'Lili Trumper', 0, 1, 0, 6565);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31099, N'Margoth Levin', 0, 1, 0, 6566);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31100, N'Sofía Gutman de Landman', 0, 1, 0, 6567);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31101, N'Bloj Jorge', 0, 1, 0, 6568);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31102, N'Isaac y Shanke Cociovich de Kaplan', 0, 1, 0, 6569);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31103, N'311', 0, 1, 0, 6569);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31104, N'Waxemberg Liliana', 0, 1, 0, 6569);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31105, N'Adi Kurdobrin', 0, 1, 0, 6570);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31106, N'Kurman Nám', 0, 1, 0, 6571);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31107, N'Acosta Fabián', 0, 1, 0, 6572);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31108, N'Saúl Ovidio Kleiman', 0, 1, 0, 6573);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31109, N'Eduardo Boeris', 0, 1, 0, 6574);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31110, N'Sara Arcavi', 0, 1, 0, 6575);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31111, N'Flia. Kurdobrin', 0, 1, 0, 6576);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31112, N'Berta de Singer', 0, 1, 0, 6577);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31113, N'yo', 0, 1, 0, 6578);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31114, N'Yolanda (Yoli) Rotemberg', 0, 1, 0, 6578);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31115, N'Wapñasky David', 0, 1, 0, 6579);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31116, N'Sara Kanzepolsky', 0, 1, 0, 6580);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31117, N'Raquel Kaplan', 0, 1, 0, 6581);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31118, N'Sofía y Eva Berdichevsky', 0, 1, 0, 6582);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31119, N'Taibe y Feigue Kaplan de Trumper', 0, 1, 0, 6583);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31120, N'Dres. Alberto y Alicia Kaplan', 0, 1, 0, 6584);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31121, N'ABRAHAM WAPSHNAIDER', 0, 1, 0, 6585);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31122, N'Jacob Migovsky', 0, 1, 0, 6586);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31123, N'Abraham Reisin', 0, 1, 0, 6587);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31124, N'Carlos Goldgrub', 0, 1, 0, 6588);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31126, N'Bernardo Rabinsky', 0, 1, 0, 6590);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31127, N'Doris Szabo de Goldstein', 0, 1, 0, 6591);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31128, N'Emilia Tognola de Ambasch (Tati)', 0, 1, 0, 6592);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31129, N'Clara Galagovsky de Monasterky', 0, 1, 0, 6593);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31130, N'Felipe Fistemberg', 0, 1, 0, 6594);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31132, N'Bianchi Ester', 0, 1, 0, 6596);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31133, N'Ricardo Feierstein', 0, 1, 0, 6597);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31134, N'Stephen A. Sadow', 0, 1, 0, 6598);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31135, N'Pablo Smulovich', 0, 1, 0, 6599);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31136, N'Adolfo Liberchuk', 0, 1, 0, 6600);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31137, N'Estela Maris de Bravé', 0, 1, 0, 6601);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31138, N'Gregorio Tauber', 0, 1, 0, 6602);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31139, N'Lorne Blumer', 0, 1, 0, 6603);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31140, N'Susana Campos', 0, 1, 0, 6604);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31141, N'Isaac Melman', 0, 1, 0, 6605);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31142, N'Liliana Arcavi', 0, 1, 0, 6606);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31143, N'Ruth de Galagovsky', 0, 1, 0, 6607);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31144, N'Sara Katz Kramnetz', 0, 1, 0, 6608);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31145, N'Kurt Rosenthal', 0, 1, 0, 6609);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31146, N'Comisión Fiesta de Moisés Ville', 0, 1, 0, 6610);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31147, N'Dr. Salomón Dosoretz', 0, 1, 0, 6610);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31148, N'Fritz Morgendorff', 0, 1, 0, 6611);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31149, N'Abraham Berstein', 0, 1, 0, 6612);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31150, N'Matilde Inés Stifelman', 0, 1, 0, 6613);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31151, N'Salomón Hammerschlag', 0, 1, 0, 6614);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31152, N'Santiago Francisco Preser', 0, 1, 0, 6615);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31153, N'José Tarlovsky', 0, 1, 0, 6616);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31155, N'Ernesto Ricardo Aguirre', 0, 1, 0, 6618);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31156, N'Aida Yedlin', 0, 1, 0, 6619);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31157, N'Raquel y José Galagovsky', 0, 1, 0, 6620);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31158, N'Rosita Bodovosof de Kaplan', 0, 1, 0, 6622);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31159, N'Sandra Rosemblit', 0, 1, 0, 6623);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31160, N'Akiva Waxemberg', 0, 1, 0, 6624);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31161, N'Arq. Mario Werbin', 0, 1, 0, 6625);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31162, N'Matilde Wapñarsky  de Bloj', 0, 1, 0, 6626);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31163, N'Isidoro Fridman', 0, 1, 0, 6627);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31164, N'Bernardo Mularz', 0, 1, 0, 6628);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31165, N'tob', 0, 1, 0, 6629);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31166, N'tobi', 0, 1, 0, 6629);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31167, N'Sara y Tobias Adler', 0, 1, 0, 6629);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31168, N'Arq. Daniel  Weisburd', 0, 1, 0, 6630);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31170, N'Congregación Israelita "Barón Hirsch"', 0, 1, 0, 6631);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31171, N'Coop. Tamberos Unidos de Wavelberg', 0, 1, 0, 6631);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31173, N'Hilda Trumper', 0, 1, 0, 6888);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31174, N'Seminario de Maestros Hebreos Iosef Draznin', 0, 1, 0, 6889);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31175, N'Eva J de', 0, 1, 0, 6889);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31176, N'Eva J. de Kivetz', 0, 1, 0, 6889);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31178, N'Barg', 0, 1, 0, 6890);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31179, N'Krupik', 0, 1, 0, 6890);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31182, N'Moisés Galagovsky', 0, 1, 0, 6891);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31184, N'Elena Berteico', 0, 1, 0, 6890);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31185, N'Orlando Cuniglio', 0, 1, 0, 6891);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31186, N'Malka Goldstein', 0, 1, 0, 6892);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31187, N'Escuela I', 0, 1, 0, 6893);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31188, N'Escuela Iahaduth', 0, 1, 0, 6893);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31189, N'teitela', 0, 1, 0, 6893);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31190, N'teitelab', 0, 1, 0, 6893);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31191, N'Jarovsky Delia', 0, 1, 0, 6893);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31192, N'Tissembaum Luis', 0, 1, 0, 6894);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31193, N'Smulovit', 0, 1, 0, 6895);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31194, N'Smulovitz', 0, 1, 0, 6895);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31195, N'Ballhorn Belkys', 0, 1, 0, 6895);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31196, N'Carlota Zinger', 0, 1, 0, 6896);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31197, N'Cecilia Delbino', 0, 1, 0, 6897);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31198, N'Uri Sevi', 0, 1, 0, 6898);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31199, N'Anilda Krilich', 0, 1, 0, 6899);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31200, N'Centro de Jubilados y Pensionados', 0, 1, 0, 6900);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31201, N'Scoie', 0, 1, 0, 6901);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31202, N'Sci', 0, 1, 0, 6901);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31203, N'Scie', 0, 1, 0, 6901);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31204, N'SEMINARIO YAHADUTH', 0, 1, 0, 6901);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31206, N'Gaa', 0, 1, 0, 6902);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31208, N'Gagn', 0, 1, 0, 6902);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31209, N'Ganadro', 0, 1, 0, 6902);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31210, N'Grupo Nitzanim', 0, 1, 0, 7955);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31211, N'Gruppp', 0, 1, 0, 7956);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31212, N'MUas', 0, 1, 0, 7956);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31213, N'Cooperativa Tamberos de Algarrobal Monigotes', 0, 1, 0, 7956);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31214, N'Comisión Cincuentenario Moisés Ville', 0, 1, 0, 7956);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31215, N'Club Atlético Argentino', 0, 1, 0, 7956);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31216, N'beit', 0, 1, 0, 7957);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31217, N'beith', 0, 1, 0, 7957);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31218, N'beit h', 0, 1, 0, 7957);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31219, N'La Mutua Agricola Ltda.', 0, 1, 0, 7957);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31220, N'S0', 0, 1, 0, 7957);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31221, N'Antonio Sorasio', 0, 1, 0, 7957);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31222, N'Arman', 0, 1, 0, 7957);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31223, N'Armando Horacio', 0, 1, 0, 7957);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31224, N'Hug', 0, 1, 0, 7957);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31225, N'Hugo', 0, 1, 0, 7957);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31226, N'Hugo Astore', 0, 1, 0, 7957);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31227, N'Kant', 0, 1, 0, 7957);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31228, N'EiK', 0, 1, 0, 7957);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31229, N'geros', 0, 1, 0, 7957);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31230, N'Sanchez Avelina (Meri)', 0, 1, 0, 1);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31231, N'Diana Zadunaisky', 0, 1, 0, 2);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31232, N'Gerosn+', 0, 1, 0, 2);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31233, N'Diana Zadunaisky', 0, 1, 0, 2);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31234, N'Andrea Farías de  Allochis', 0, 1, 0, 3);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31235, N'Leah Langleben', 0, 1, 0, 4);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31236, N'Viviana Hirsch Birkenfeld', 0, 1, 0, 5);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31237, N'Wolff', 0, 1, 0, 6);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31238, N'trop', 0, 1, 0, 6);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31239, N'Solita Katz', 0, 1, 0, 6);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31240, N'cr', 0, 1, 0, 6);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31241, N'Cristina Arralde', 0, 1, 0, 6);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31242, N'Angela Ibañez', 0, 1, 0, 7);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31243, N'Felipe Teitelbaum', 0, 1, 0, 8);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31244, N'Isaías Gun', 0, 1, 0, 9);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31245, N'Richiger Hnos', 0, 1, 0, 10);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31246, N'Eva  Lind', 0, 1, 0, 11);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31247, N'Armando Wolf', 0, 1, 0, 12);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31248, N'Gorboin Flora', 0, 1, 0, 13);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31249, N'Esther Glasberg', 0, 1, 0, 14);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31250, N'Naúm', 0, 1, 0, 15);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31251, N'Guenz', 0, 1, 0, 15);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31252, N'Zelda Trajtemberg', 0, 1, 0, 15);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31253, N'<f', 0, 1, 0, 16);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31254, N'La  m', 0, 1, 0, 16);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31255, N'Sergio Acosta', 0, 1, 0, 16);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31256, N'Sergio Acosta', 0, 1, 0, 16);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31257, N'Haim Avni', 0, 1, 0, 17);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31258, N'Matilde R', 0, 1, 0, 18);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31259, N'Hilel Resnizky', 0, 1, 0, 19);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31260, N'Tissembaum Isaac', 0, 1, 0, 20);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31261, N'Leonardo Strejilevich', 0, 1, 0, 20);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31262, N'Rose Auslander', 0, 1, 0, 21);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31263, N'Alberto Mazor', 0, 1, 0, 22);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31264, N'Antonio Elio Brailovsky', 0, 1, 0, 23);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31265, N'Daniel J. Imfeld', 0, 1, 0, 24);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31266, N'Patricia Nobilia', 0, 1, 0, 25);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31267, N'Ole Winther', 0, 1, 0, 26);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31268, N'Jose Luis Raota', 0, 1, 0, 27);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31269, N'Dario Macor', 0, 1, 0, 28);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31270, N'Maria Angelica Zanabria', 0, 1, 0, 29);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31271, N'Celia Gladys Lopez', 0, 1, 0, 30);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31272, N'Israel Gutman', 0, 1, 0, 31);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31273, N'Itzhak B. Tatelbaum', 0, 1, 0, 32);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31274, N'Alicia Steimberg', 0, 1, 0, 33);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31275, N'Elio Kapszuk', 0, 1, 0, 34);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31276, N'Alan Fournier', 0, 1, 0, 35);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31277, N'Silvia Iparraguirre', 0, 1, 0, 36);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31278, N'Osvaldo Baigorria', 0, 1, 0, 37);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31279, N'Benjamin Roisinblit', 0, 1, 0, 38);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31280, N'P. Erlich', 0, 1, 0, 39);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31281, N'Maria del Carmen Palomeque', 0, 1, 0, 40);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31282, N'Rut Jarmatz', 0, 1, 0, 41);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31283, N'Ramon Sopena', 0, 1, 0, 42);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31284, N'Luis Orlandini', 0, 1, 0, 43);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31285, N'Marcelo Kohan', 0, 1, 0, 44);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31286, N'Moliere', 0, 1, 0, 45);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31287, N'Marcelo S', 0, 1, 0, 46);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31288, N'Marcelo Sili', 0, 1, 0, 46);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31289, N'Javier Sinay', 0, 1, 0, 47);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31290, N'Lazaro Schallman', 0, 1, 0, 48);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31291, N'Simja Sneh', 0, 1, 0, 49);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31292, N'Jonas Turkow', 0, 1, 0, 50);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31293, N'Itzhak Grynbaum', 0, 1, 0, 51);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31294, N'Teodoro Herzl', 0, 1, 0, 52);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31295, N'León Dujovne', 0, 1, 0, 53);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31296, N'Jaime Barylko', 0, 1, 0, 54);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31297, N'Aarón Steinberg', 0, 1, 0, 55);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31298, N'Yosef Avidar', 0, 1, 0, 56);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31299, N'Ernst Cassirer', 0, 1, 0, 57);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31300, N'Maria Laura San Martín', 0, 1, 0, 58);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31301, N'Adriana Imhoff', 0, 1, 0, 59);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31302, N'Dominique Frischer', 0, 1, 0, 60);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31303, N'Benjamin Edelstein', 0, 1, 0, 61);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31305, N'Doris Kaplan', 0, 1, 0, 62);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31306, N'Lidia Lewczuk de Masalyka', 0, 1, 0, 62);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31307, N'Dr. Carlos Daniel Dabul', 0, 1, 0, 63);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31308, N'Abel Basti', 0, 1, 0, 64);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31309, N'berns', 0, 1, 0, 65);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31310, N'Comisión centenario Moisés Ville', 0, 1, 0, 65);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31311, N'Sergio Acosta', 0, 1, 0, 65);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31313, N'cant', 0, 1, 0, 65);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31314, N'Armando Bublik', 0, 1, 0, 65);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31315, N'Lydia Mrejen', 0, 1, 0, 66);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31316, N'sarf', 0, 1, 0, 67);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31317, N'Ziperovich', 0, 1, 0, 67);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31318, N'Soni', 0, 1, 0, 67);
INSERT INTO PERSONAS (cod, dsc, codpersrel, tipopers, codorigen, fila) VALUES (31319, N'Sonia Sabena', 0, 1, 0, 67);
-- 530 records

--
-- Table structure for table 'PIEZAS'
--
