use moisesville;

delete from coleccion where id > -1;

insert into coleccion(id, nombre) values(0,'Sin colección');
insert into coleccion(id, nombre) values(2,'Centenario Moises Ville');
insert into coleccion(id, nombre) values(7,'Moisés Ville');
insert into coleccion(id, nombre) values(12,'Instituciones Locales');
insert into coleccion(id, nombre) values(13,'70 aniversario de Moisés Ville.');
insert into coleccion(id, nombre) values(17,'WIZO');
insert into coleccion(id, nombre) values(19,'Orígenes');
insert into coleccion(id, nombre) values(21,'Instituciones');
insert into coleccion(id, nombre) values(22,'Socorro Fraternal');
insert into coleccion(id, nombre) values(23,'Sociedad Kadima');
insert into coleccion(id, nombre) values(24,'Hospital Barón Hirsch');
insert into coleccion(id, nombre) values(25,'Escuela Fiscal Nº 462');
insert into coleccion(id, nombre) values(27,'Escuela Iahaduth');
insert into coleccion(id, nombre) values(29,'La Mutua');
insert into coleccion(id, nombre) values(30,'Inmigración');
insert into coleccion(id, nombre) values(31,'Evolución Técnica');
insert into coleccion(id, nombre) values(35,'Aniversarios');
insert into coleccion(id, nombre) values(37,'Cincuentenarios');
insert into coleccion(id, nombre) values(38,'Mujeres de la Colonia');
insert into coleccion(id, nombre) values(40,'Artesanos');
insert into coleccion(id, nombre) values(42,'Hajshará');
insert into coleccion(id, nombre) values(43,'Judaica');
insert into coleccion(id, nombre) values(44,'colección león Silberman');
insert into coleccion(id, nombre) values(45,'Escuelas');
insert into coleccion(id, nombre) values(47,'COMUNIDAD MUTUAL ISRAELITA');
insert into coleccion(id, nombre) values(48,'Ganaderos Unidos S.A.');
insert into coleccion(id, nombre) values(51,'Moisés Ville y Colonia');
insert into coleccion(id, nombre) values(52,'Barck');
insert into coleccion(id, nombre) values(54,'Vida Cultural');
insert into coleccion(id, nombre) values(55,'110 Aniversario de Moisés Ville');
insert into coleccion(id, nombre) values(56,'colección  Israel');
insert into coleccion(id, nombre) values(59,'Medios de comunicación');
insert into coleccion(id, nombre) values(61,'Juan Luis Tenembaum');
insert into coleccion(id, nombre) values(63,'Museo Rabino Aarón Goldman');
insert into coleccion(id, nombre) values(65,'colección Frida Gutman');
insert into coleccion(id, nombre) values(68,'Religión');
insert into coleccion(id, nombre) values(69,'Ejemplares de El Alba');
insert into coleccion(id, nombre) values(70,'Coop. Tamberos Unidos de Wavelberg');
insert into coleccion(id, nombre) values(71,'MILA');
insert into coleccion(id, nombre) values(72,'Familia de Moisés Ville');
insert into coleccion(id, nombre) values(73,'Museo -  Escuela');
insert into coleccion(id, nombre) values(74,'Aniversario de los 120 años');
insert into coleccion(id, nombre) values(75,'"Fiesta de Moisés Ville ""Cuna de Integración Cultur"');
insert into coleccion(id, nombre) values(76,'Muestra en museo');
insert into coleccion(id, nombre) values(77,'colección Ziperovich');
insert into coleccion(id, nombre) values(78,'Holocausto');

