use moisesville;

insert into tema(id,nombre) values(9,'Campaña Solidaria');
insert into tema(id,nombre) values(10,'Casamiento');
insert into tema(id,nombre) values(11,'Centenarios');
insert into tema(id,nombre) values(18,'AGRICULTURA');
insert into tema(id,nombre) values(23,'Inmigración');
insert into tema(id,nombre) values(24,'Instituciones');
insert into tema(id,nombre) values(25,'Bancos');
insert into tema(id,nombre) values(28,'La Mutua Agricola');
insert into tema(id,nombre) values(29,'Moises Ville-Vida familiar');
insert into tema(id,nombre) values(33,'Moisés Ville-Asentamiento');
insert into tema(id,nombre) values(35,'temática Periodistica');
insert into tema(id,nombre) values(36,'Orígenes');
insert into tema(id,nombre) values(39,'Las Sinagogas');
insert into tema(id,nombre) values(40,'Obras de Moisés Ville');
insert into tema(id,nombre) values(42,'Vida Social');
insert into tema(id,nombre) values(43,'Travesía');
insert into tema(id,nombre) values(49,'Moisés Ville y Colonia');
insert into tema(id,nombre) values(51,'Artesanos');
insert into tema(id,nombre) values(52,'Colonización Judía en la Argentina');
insert into tema(id,nombre) values(58,'Las doce casa - Wabelberg');
insert into tema(id,nombre) values(59,'Moisés Ville - Orígenes');
insert into tema(id,nombre) values(64,'Comercios');
insert into tema(id,nombre) values(65,'Artículo del Hogar');
insert into tema(id,nombre) values(67,'Escuelas');
insert into tema(id,nombre) values(70,'Teatro');
insert into tema(id,nombre) values(71,'Fábrica');
insert into tema(id,nombre) values(72,'Residentes');
insert into tema(id,nombre) values(73,'Objetos  rituales');
insert into tema(id,nombre) values(75,'Personajes de la Colonia');
insert into tema(id,nombre) values(76,'Seminario');
insert into tema(id,nombre) values(77,'Profesionales');
insert into tema(id,nombre) values(78,'arma');
insert into tema(id,nombre) values(81,'Sastrería');
insert into tema(id,nombre) values(84,'Distinción al mérito');
insert into tema(id,nombre) values(85,'Documentos Religiosos');
insert into tema(id,nombre) values(89,'Fotógrafo');
insert into tema(id,nombre) values(91,'Sodería Malajovich');
insert into tema(id,nombre) values(94,'Cooperativismo');
insert into tema(id,nombre) values(97,'Presentación de Libro');
insert into tema(id,nombre) values(98,'110 Aniversario de Moisés Ville');
insert into tema(id,nombre) values(103,'Cincuentenario de Moisés Ville');
insert into tema(id,nombre) values(104,'Estatuto');
insert into tema(id,nombre) values(105,'Medios de Comunicación');
insert into tema(id,nombre) values(106,'Contrato');
insert into tema(id,nombre) values(107,'Isologotipo');
insert into tema(id,nombre) values(110,'Cincuentenarios');
insert into tema(id,nombre) values(111,'Visita del Embajador de Israel');
insert into tema(id,nombre) values(116,'Granja Hajshara');
insert into tema(id,nombre) values(117,'Homenajes y festejos');
insert into tema(id,nombre) values(118,'Plaza de Moisés Ville');
insert into tema(id,nombre) values(119,'Al rescate de nuestra identidad');
insert into tema(id,nombre) values(120,'Instrumento de medicina');
insert into tema(id,nombre) values(121,'Familia de Moisés Ville');
insert into tema(id,nombre) values(122,'Moisés Ville');
insert into tema(id,nombre) values(123,'Antisemitismo');
insert into tema(id,nombre) values(124,'Memorias de Moisés Ville');
insert into tema(id,nombre) values(125,'Al rescate de nuestra Identidad');
insert into tema(id,nombre) values(126,'Documental');
insert into tema(id,nombre) values(127,'Asociación de Museos');
insert into tema(id,nombre) values(128,'Día Internacional de los Museos');
insert into tema(id,nombre) values(129,'Inauguración');
insert into tema(id,nombre) values(130,'Club Atlético Argentino');
insert into tema(id,nombre) values(131,'Maquinarias');
insert into tema(id,nombre) values(132,'calendarios');
insert into tema(id,nombre) values(133,'Muestra');
insert into tema(id,nombre) values(134,'Proyecto');
insert into tema(id,nombre) values(135,'Despedida de año');
insert into tema(id,nombre) values(136,'Escuela El Hogar');
insert into tema(id,nombre) values(137,'Bosque centenario');
insert into tema(id,nombre) values(138,'Día Internacional de Directores de Museos');
insert into tema(id,nombre) values(139,'Artículo del hogar');
insert into tema(id,nombre) values(140,'JCA');
insert into tema(id,nombre) values(141,'Ejército');
insert into tema(id,nombre) values(142,'Holocausto');